"""
FastAPI inference service for the crop disease classifier.

Run locally with:
    uvicorn src.api.main:app --reload --port 8000

Then open http://localhost:8000/docs for interactive API documentation
(auto-generated by FastAPI from the Pydantic schemas in schemas.py).
"""

import io
import time

from fastapi import FastAPI, File, HTTPException, UploadFile
from PIL import Image, UnidentifiedImageError

from src.api.inference import DiseasePredictor
from src.api.monitoring import get_metrics, record_prediction
from src.api.schemas import ClassPrediction, HealthResponse, PredictionResponse

app = FastAPI(
    title="Crop Disease Detector API",
    description="Upload a leaf image, get back a predicted disease classification.",
    version="1.0.0",
)

# Loaded once at module import time (i.e. once when the server starts), not
# per-request. See the docstring in inference.py for why this matters.
predictor = DiseasePredictor()

MAX_FILE_SIZE_MB = 10
ALLOWED_CONTENT_TYPES = {"image/jpeg", "image/png", "image/jpg", "image/webp"}


@app.get("/health", response_model=HealthResponse)
def health_check():
    """
    Basic liveness/readiness check. Cloud platforms and load balancers
    ping this endpoint to know whether the service is up and the model is
    actually loaded before routing real traffic to it.
    """
    return HealthResponse(
        status="ok",
        model_loaded=predictor.model is not None,
        num_classes=len(predictor.class_names),
    )


@app.post("/predict", response_model=PredictionResponse)
async def predict(file: UploadFile = File(...)):
    """
    Accepts an uploaded image file, returns the predicted disease class plus
    a confidence score and the top-3 alternative predictions.
    """
    if file.content_type not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type '{file.content_type}'. Allowed: {ALLOWED_CONTENT_TYPES}",
        )

    file_bytes = await file.read()

    if len(file_bytes) > MAX_FILE_SIZE_MB * 1024 * 1024:
        raise HTTPException(status_code=400, detail=f"File too large. Max size: {MAX_FILE_SIZE_MB}MB")

    try:
        image = Image.open(io.BytesIO(file_bytes))
    except UnidentifiedImageError:
        raise HTTPException(status_code=400, detail="Could not read file as an image.")

    start_time = time.perf_counter()
    predictions = predictor.predict(image, top_k=3)
    latency_ms = (time.perf_counter() - start_time) * 1000

    top_class, top_confidence = predictions[0]

    # Record this prediction for the /metrics endpoint. Deliberately done
    # AFTER the response is computed so a monitoring bug can never break
    # or slow down an actual prediction request.
    record_prediction(predicted_class=top_class, confidence=top_confidence, latency_ms=latency_ms)

    return PredictionResponse(
        predicted_class=top_class,
        confidence=top_confidence,
        top_predictions=[
            ClassPrediction(class_name=name, confidence=conf) for name, conf in predictions
        ],
    )


@app.get("/metrics")
def metrics():
    """
    Basic operational metrics: request volume, average latency/confidence,
    and which classes are being predicted most often. See monitoring.py for
    the honest caveat that this is in-memory only (resets on restart).
    """
    return get_metrics()